config:
  worldCellWidth: 20
  worldCellHeight: 40
  spriteWidth: 128
  spriteHeight: 128
  viewWidth: 7
  viewHeight: 10
  viewLeft: -3
  viewTop: -4
  # viewWidth: 20
  # viewHeight: 30
  movementTweenSpeed: 500
  controls:
    swipeThumbSize: 30
    minSwipeDist: 50
    directionSnaps: 4
  player:
    hp: 4
    move:
      speed: 10
    inventory:
      activeSlot: 0
      slots:
        - item: 1 # pick
          level: 0
          itemCount: -1
        - item: 4 # platform
          level: 0
          itemCount: 8
        - item: 2 # sword
          level: 0
          itemCount: 10
        - item: 1 # pick
          level: 2
          itemCount: -1
  map:
    useSheetMap: true
    blockMap: # 0=air, 1=dirt, 2=ctone, 3=rock
      - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      - [1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      - [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1]
      - [1, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 1, 3, 1, 1, 1, 1, 1, 1]
      - [1, 2, 3, 1, 1, 1, 0, 0, 0, $2, 2, 1, 2, 1, 2, 1, 3, 2, 1, 1]
      - [1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1]
      - [1, 1, 2, $1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 0, 0, 0, 2, 1, 1]
      - [1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 2, 2, 0, 0, 1, 1, 2]
      - [1, 1, 3, 2, 1, 1, 2, 1, 1, 3, 2, 1, 2, 1, 1, 2, 0, 0, $1, 2]
      - [1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 0, 1, 1]
      - [2, 1, 2, 1, 1, 0, 2, 2, 2, 1, $2, 2, 2, 2, 2, 2, 2, 2, 1, 2]
      - [2, 2, 2, 0, 0, 1, 2, 3, 3, 1, 2, 3, 3, 2, 2, 2, 3, 2, 1, 2]
      - [2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 2, 3, 3, 1, 2, 2, 2, 2]
      - [1, 1, 2, 2, 2, 3, $2, 2, 1, 1, 1, 2, 1, 3, $4, 0, 0, 0, 2, 2]
      - [2, 2, 1, 2, 2, 2, 1, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      - [2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1]
      - [2, 3, 1, 3, 3, 3, 1, 3, 3, 3, 2, 3, 1, 2, 1, 1, 3, $2, 3, 1]
      - [2, 3, 3, 3, 3, 1, 3, 2, 3, 3, $2, 3, 1, 3, 3, 3, 3, 3, 3, 1]
      - [1, 0, 0, 0, 3, 1, 2, 2, 3, 3, 3, 2, 3, 1, 2, 2, 2, 2, 1, 2]
      - [3, 0, 0, 0, 3, 3, 0, 0, 0, 3, 2, 0, 0, 0, 1, 3, 3, 3, 3, 3]
      - [3, 3, 0, 0, 0, 3, 0, 0, 0, 3, 1, 3, 3, 3, $2, 3, 1, 3, 1, 3]
      - [2, 2, 2, 1, 3, 3, $4, 0, 0, 0, 0, 3, 1, 2, 3, 2, 1, 1, 4, 4]
      - [2, 3, 3, 1, 3, 4, 4, 1, 3, 2, 2, 1, 1, 3, 1, 2, 3, 4, 4, 2]
      - [2, 2, 3, 3, 1, 1, 4, 4, 4, 4, 3, 4, 4, 4, 4, 2, 2, 1, 1, 1]
      - [4, 4, 2, 1, 3, 3, 3, 3, 3, 1, 4, 4, 1, 2, 3, 2, 1, 1, 2, 2]
      - [3, 4, 4, 3, 1, 2, 1, 3, 1, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3]
      - [2, 3, 4, 4, 3, 3, 3, 1, 3, 2, 2, 1, 1, 3, $4, 2, 3, 1, 1, 2]
      - [3, 1, 1, 3, 1, 2, 1, 3, 1, 3, 4, 4, 1, 3, 1, 3, 3, 3, 3, 3]
      - [2, 1, 1, 1, 3, 1, 1, 1, $2, 3, 1, 1, 4, 4, 4, 4, 2, 1, 1, 1]
      - [2, 3, 3, 1, 3, 4, 4, 1, 3, 2, 2, 1, 1, 3, 1, 2, $2, 4, 4, 2]
      - [2, 2, 3, 3, 1, 1, 4, 4, 4, 4, 3, 4, 4, 4, 4, 2, 2, 1, 1, 1]
      - [4, 4, 2, 1, 3, 3, 3, 3, 3, 1, 4, 4, 1, 2, 3, 2, 1, 1, 2, 2]
      - [3, 4, 4, $2, 1, 2, 1, 3, 1, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3]
      - [2, 3, 4, 4, 3, 3, 3, 1, 3, 2, 2, 1, 1, 3, $4, 2, 3, 1, 1, 2]
      - [2, 2, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 1, 1, 1, 2, 2]
      - [2, 1, 1, 1, 3, 1, $5, 1, 1, 3, 1, 1, 4, 4, 4, 4, $2, 1, 1, 1]
      - [2, 3, 3, 3, 3, $2, 3, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1]
      - [2, 3, 3, 1, 3, 4, 4, 1, 3, 2, 2, 1, 0, 0, 0, 2, 3, 4, 4, 2]
      - [2, 2, 3, 3, 1, 1, 4, 4, 4, 4, 3, 4, 4, 4, 4, 2, 0, 0, 0, 1]

#  ██████  ██       ██████   ██████ ██   ██ ███████ 
#  ██   ██ ██      ██    ██ ██      ██  ██  ██      
#  ██████  ██      ██    ██ ██      █████   ███████ 
#  ██   ██ ██      ██    ██ ██      ██  ██       ██ 
#  ██████  ███████  ██████   ██████ ██   ██ ███████ 
#                                                   
  blocks:
    0:
      name: air
      type: air
      key: ''
      frame: ''
    1:
      name: dirt
      type: solid
      key: 'spritesheet_tiles'
      frame: 'dirt'
      solid:
        strength: 1
    2:
      name: stone
      type: solid
      key: 'spritesheet_tiles'
      frame: 'stone'
      solid:
        strength: 2
    3:
      name: rock
      type: solid
      key: 'spritesheet_tiles'
      frame: 'greystone'
      solid:
        strength: 3
    4:
      name: obsidian
      type: solid
      key: 'spritesheet_tiles'
      frame: 'snow'
      solid:
        strength: 10
    5:
      name: platform
      type: platform
      key: 'spritesheet_complete'
      frame: 'bridgeA'
    6:
      name: chest
      type: chest
      key: 'spritesheet_complete'
      frame: 'boxCrate_double'
    7:
      name: spike
      type: trap
      key: 'spritesheet_complete'
      frame: 'spikes'

#  ███████ ███    ██ ███████ ███    ███ ██ ███████ ███████ 
#  ██      ████   ██ ██      ████  ████ ██ ██      ██      
#  █████   ██ ██  ██ █████   ██ ████ ██ ██ █████   ███████ 
#  ██      ██  ██ ██ ██      ██  ██  ██ ██ ██           ██ 
#  ███████ ██   ████ ███████ ██      ██ ██ ███████ ███████ 
#                                                          
  enemies:
    0: 
      enemyName: spike
      behaviors: [trap]
      key: 'spritesheet_complete'
      frame: 'spikes'
      trap:
        accuracy: 100 # percent
        damage:
          physical: 1
    1: 
      enemyName: slime
      behaviors: [queue, move, gravity, faceLeftRight] # passiveAttack]
      key: 'spritesheet_complete'
      frame: 'slimeBlue'
      queue:
        queue: true
      move:
        directions: [0, 4] # 0=right, 4=left
        speed: 10
      faceLeftRight:
        spriteFacingRight: false
        startFacingRight: true
      gravity:
        type: simple # simple = fall straight to bottom; float = fall once per turn, can move in air
      # passiveAttack: # does not aggro, but can chase
      #   speed: 10
      #   accuracy: 100 # percent
      #   damage:
      #     physical: 1
      #     knock: undo
      #   chase:
      #     vision: 5 # -1 = infinity
          # fromSpawn: 5 # -1 = infinity
      

#  ██ ████████ ███████ ███    ███ ███████ 
#  ██    ██    ██      ████  ████ ██      
#  ██    ██    █████   ██ ████ ██ ███████ 
#  ██    ██    ██      ██  ██  ██      ██ 
#  ██    ██    ███████ ██      ██ ███████ 
#                                         
  items:
    0:
      name: ' '
      types: []
      sprites: 
        - key: ''
          frame: ''
      maxStack: [-1]
    1:
      name: pick
      types: [mining]
      sprites: 
        - key: 'spritesheet_items'
          frame: 'pick_bronze'
        - key: 'spritesheet_items'
          frame: 'pick_silver'
        - key: 'spritesheet_items'
          frame: 'pick_gold'
      maxStack: [999]
      mining:
        strength: [1, 2, 3]
    2:
      name: sword
      types: [fight]
      sprites: 
        - key: 'spritesheet_items'
          frame: 'sword_bronze'
        - key: 'spritesheet_items'
          frame: 'sword_silver'
        - key: 'spritesheet_items'
          frame: 'sword_gold'
      maxStack: [999]
      fight:
        strength: [1, 2, 3]
    3:
      name: war_hammer
      types: [mining, fight]
      sprites:
        - key: 'spritesheet_items'
          frame: 'hammer_bronze'
        - key: 'spritesheet_items'
          frame: 'hammer_silver'
        - key: 'spritesheet_items'
          frame: 'hammer_gold'
      maxStack: [999]
      fight:
        strength: [1, 1, 2]
      mining:
        strength: [1, 2, 2]
    4:
      name: platform
      types: [block]
      sprites: 
        - key: 'spritesheet_complete'
          frame: 'bridgeA'
          scale: 0.5
      maxStack: [20]
      block:
        builds: 5 # platform

#  ███████ ███    ██ ████████ ██ ████████ ██ ███████ ███████ 
#  ██      ████   ██    ██    ██    ██    ██ ██      ██      
#  █████   ██ ██  ██    ██    ██    ██    ██ █████   ███████ 
#  ██      ██  ██ ██    ██    ██    ██    ██ ██           ██ 
#  ███████ ██   ████    ██    ██    ██    ██ ███████ ███████ 
#                                                            
  entities:
    0:
      name: cave
      type: chest
      chest:
        key: 'spritesheet_complete'
        frame: 'window'
        size: 4
    1:
      name: drop_pick+1 x10
      type: drop
      drop:
        item: 1
        level: 1
        itemCount: 10
    2:
      name: drop_platform x8
      type: drop
      drop:
        item: 4
        level: 0
        itemCount: 8
    3:
      name: chest+4
      type: chest
      chest:
        key: 'spritesheet_complete'
        frame: 'boxCrate_double'
        size: 4
    4:
      name: drop_pick+2 x10
      type: drop
      drop:
        item: 1
        level: 2
        itemCount: 10
    5:
      name: drop_pick+2 x999
      type: drop
      drop:
        item: 1
        level: 2
        itemCount: 999
    6:
      name: spike
      type: enemy
      enemy:
        enemyID: 0 # spike
    7:
      name: slime
      type: enemy
      enemy:
        enemyID: 1 # slime
  
#   ██████ ██████  ███████ ██████  ██ ████████ ███████ 
#  ██      ██   ██ ██      ██   ██ ██    ██    ██      
#  ██      ██████  █████   ██   ██ ██    ██    ███████ 
#  ██      ██   ██ ██      ██   ██ ██    ██         ██ 
#   ██████ ██   ██ ███████ ██████  ██    ██    ███████ 
#                                                      
  credits:
    - title: Game Design, Programming
      names:
        - Dickson Chui (@vicksonzero)
    - title: Majority of Graphics; Art style
      names:
        - kenney.nl
    - title: Graphics
      names:
        - Dickson Chui
    - title: Music / Sound
      names:
        - none yet
    - title: Items Design Ideas
      names:
        - Amethyst
        - choiwaikit0613
        - icebee










