config:
  spriteWidth: 128
  spriteHeight: 128
  viewWidth: 5
  viewHeight: 7
  movementTweenSpeed: 500
  # 0=air, 1=dirt, 2=ctone, 3=rock
  blockMap:
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    - [2, 3, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    - [1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1]
    - [1, 3, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 3, 1, 1, 1, 1, 1, 1]
    - [1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 3, 2, 1, 1]
    - [1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]
    - [1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1]
    - [1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2]
    - [1, 1, 3, 2, 1, 1, 2, 1, 1, 3, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2]
    - [1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1]
    - [2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2]
    - [2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 3, 2, 1, 2]
    - [2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2]
    - [1, 1, 2, 2, 2, 3, 1, 2, 1, 1, 1, 2, 1, 3, 2, 2, 2, 2, 2, 2]
    - [2, 2, 1, 2, 2, 2, 1, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    - [2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1]
    - [2, 3, 1, 3, 3, 3, 1, 3, 3, 3, 2, 3, 1, 2, 1, 1, 3, 2, 3, 1]
    - [2, 3, 3, 3, 3, 1, 3, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1]
    - [1, 1, 2, 3, 3, 1, 2, 2, 3, 3, 3, 2, 3, 1, 2, 2, 2, 2, 1, 2]
    - [3, 1, 1, 3, 3, 2, 3, 3, 1, 3, 2, 3, 3, 3, 1, 3, 3, 3, 3, 3]
    - [3, 3, 3, 2, 3, 2, 1, 1, 3, 3, 1, 3, 3, 3, 3, 3, 1, 3, 1, 3]
    - [2, 2, 2, 1, 3, 3, 3, 3, 3, 1, 3, 3, 1, 2, 3, 2, 1, 1, 2, 2]
    - [2, 3, 3, 1, 3, 3, 3, 1, 3, 2, 2, 1, 1, 3, 1, 2, 3, 1, 1, 2]
    - [2, 2, 3, 3, 1, 1, 3, 3, 3, 1, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1]
    - [2, 2, 2, 1, 3, 3, 3, 3, 3, 1, 3, 3, 1, 2, 3, 2, 1, 1, 2, 2]
    - [3, 1, 1, 3, 1, 2, 1, 3, 1, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3]
    - [2, 3, 3, 1, 3, 3, 3, 1, 3, 2, 2, 1, 1, 3, 1, 2, 3, 1, 1, 2]
    - [3, 1, 1, 3, 1, 2, 1, 3, 1, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3]
    - [2, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1]
  blocks:
    0:
      name: air
      type: air
      sprite: 'spritesheet_tiles'
      frameName: ''
    1:
      name: dirt
      type: solid
      sprite: 'spritesheet_tiles'
      frameName: 'dirt'
    2:
      name: stone
      type: solid
      sprite: 'spritesheet_tiles'
      frameName: 'stone'
    3:
      name: rock
      type: solid
      sprite: 'spritesheet_tiles'
      frameName: 'greystone'
    4:
      name: ladder
      type: platform
      sprite: 'spritesheet_tiles'
      frameName: 'greystone'