config:
  spriteWidth: 128
  spriteHeight: 128
  viewWidth: 5
  viewHeight: 8
  # viewWidth: 20
  # viewHeight: 30
  movementTweenSpeed: 500
  controls:
    swipeThumbSize: 30
    minSwipeDist: 50
    directionSnaps: 4
  # 0=air, 1=dirt, 2=ctone, 3=rock
  blockMap:
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    - [1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    - [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1]
    - [1, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 1, 3, 1, 1, 1, 1, 1, 1]
    - [1, 2, 3, 1, 1, 1, 0, 0, 0, $2, 2, 1, 2, 1, 2, 1, 3, 2, 1, 1]
    - [1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1]
    - [1, 1, 2, $1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 0, 0, 0, 2, 1, 1]
    - [1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 2, 2, 0, 0, 1, 1, 2]
    - [1, 1, 3, 2, 1, 1, 2, 1, 1, 3, 2, 1, 2, 1, 1, 2, 0, 0, $1, 2]
    - [1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 0, 1, 1]
    - [2, 1, 2, 1, 1, 0, 2, 2, 2, 1, $2, 2, 2, 2, 2, 2, 2, 2, 1, 2]
    - [2, 2, 2, 0, 0, 1, 2, 3, 3, 1, 2, 3, 3, 2, 2, 2, 3, 2, 1, 2]
    - [2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 2, 3, 3, 1, 2, 2, 2, 2]
    - [1, 1, 2, 2, 2, 3, $2, 2, 1, 1, 1, 2, 1, 3, $4, 0, 0, 0, 2, 2]
    - [2, 2, 1, 2, 2, 2, 1, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    - [2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1]
    - [2, 3, 1, 3, 3, 3, 1, 3, 3, 3, 2, 3, 1, 2, 1, 1, 3, $2, 3, 1]
    - [2, 3, 3, 3, 3, 1, 3, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1]
    - [1, 0, 0, 0, 3, 1, 2, 2, 3, 3, 3, 2, 3, 1, 2, 2, 2, 2, 1, 2]
    - [3, 0, 0, 0, 3, 3, 0, 0, 0, 3, 2, 0, 0, 0, 1, 3, 3, 3, 3, 3]
    - [3, 3, 0, 0, 0, 3, 0, 0, 0, 3, 1, 3, 3, 3, 3, 3, 1, 3, 1, 3]
    - [2, 2, 2, 1, 3, 3, 3, 3, 0, 0, 0, 3, 1, 2, 3, 2, 1, 1, 4, 4]
    - [2, 3, 3, 1, 3, 4, 4, 1, 3, 2, 2, 1, 1, 3, 1, 2, 3, 4, 4, 2]
    - [2, 2, 3, 3, 1, 1, 4, 4, 4, 4, 3, 4, 4, 4, 4, 2, 2, 1, 1, 1]
    - [4, 4, 2, 1, 3, 3, 3, 3, 3, 1, 4, 4, 1, 2, 3, 2, 1, 1, 2, 2]
    - [3, 4, 4, 3, 1, 2, 1, 3, 1, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3]
    - [2, 3, 4, 4, 3, 3, 3, 1, 3, 2, 2, 1, 1, 3, 1, 2, 3, 1, 1, 2]
    - [3, 1, 1, 3, 1, 2, 1, 3, 1, 3, 4, 4, 1, 3, 1, 3, 3, 3, 3, 3]
    - [2, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 4, 4, 4, 4, 2, 1, 1, 1]
  blocks:
    0:
      name: air
      type: air
      key: ''
      frame: ''
    1:
      name: dirt
      type: solid
      key: 'spritesheet_tiles'
      frame: 'dirt'
      solid:
        strength: 1
    2:
      name: stone
      type: solid
      key: 'spritesheet_tiles'
      frame: 'stone'
      solid:
        strength: 2
    3:
      name: rock
      type: solid
      key: 'spritesheet_tiles'
      frame: 'greystone'
      solid:
        strength: 3
    4:
      name: obsidian
      type: solid
      key: 'spritesheet_tiles'
      frame: 'trunk_white_side'
      solid:
        strength: 10
    5:
      name: platform
      type: platform
      key: 'spritesheet_complete'
      frame: 'bridgeA'
    6:
      name: chest
      type: chest
      key: 'spritesheet_complete'
      frame: 'boxCrate_double'
  items:
    0:
      name: hand
      types: []
      sprites: 
        - key: ''
          frame: ''
    1:
      name: pick
      types: [mining]
      sprites: 
        - key: 'spritesheet_items'
          frame: 'pick_bronze'
        - key: 'spritesheet_items'
          frame: 'pick_silver'
        - key: 'spritesheet_items'
          frame: 'pick_gold'
      uses: -1
      maxStack: 1
      mining:
        strength: [1, 2, 3]
    2:
      name: sword
      types: [fight]
      sprites: 
        - key: 'spritesheet_items'
          frame: 'sword_bronze'
        - key: 'spritesheet_items'
          frame: 'sword_silver'
        - key: 'spritesheet_items'
          frame: 'sword_gold'
      uses: -1
      maxStack: 1
      fight:
        strength: [1, 2, 3]
    3:
      name: warhammer
      types: [mining, fight]
      sprites: 
        - key: 'spritesheet_items'
          frame: 'hammer_bronze'
        - key: 'spritesheet_items'
          frame: 'hammer_silver'
        - key: 'spritesheet_items'
          frame: 'hammer_gold'
      uses: 20
      maxStack: 20
      fight:
        strength: [1, 1, 2]
      mining:
        strength: [1, 2, 2]
    4:
      name: platform
      types: [block]
      sprites: 
        - key: 'spritesheet_complete'
          frame: 'bridgeA'
          scale: 0.5
      uses: 1
      maxStack: 20
      block:
        builds: 5 #ladder
  entities:
    1:
      name: drop_pick+1
      type: drop
      drop:
        item: 1
        level: 1
        count: 1
    2:
      name: drop_platform+4
      type: drop
      drop:
        item: 4
        level: 0
        count: 4
    3:
      name: chest+4
      type: chest
      chest:
        key: 'spritesheet_complete'
        frame: 'boxCrate_double'
        size: 4
    4:
      name: drop_pick+2
      type: drop
      drop:
        item: 1
        level: 2
        count: 1
      










